export const statesOfBrazil = [
  { shortName: 'AC', name: 'Acre' },
  { shortName: 'AL', name: 'Alagoas' },
  { shortName: 'AP', name: 'Amapá' },
  { shortName: 'AM', name: 'Amazonas' },
  { shortName: 'BA', name: ' Bahia' },
  { shortName: 'CE', name: 'Ceará' },
  { shortName: 'DF', name: 'Distrito Federal' },
  { shortName: 'ES', name: 'Espírito Santo' },
  { shortName: 'GO', name: 'Goiás' },
  { shortName: 'MA', name: 'Maranhão' },
  { shortName: 'MT', name: 'Mato Grosso' },
  { shortName: 'MS', name: 'Mato Grosso do Sul' },
  { shortName: 'MG', name: 'Minas Gerais' },
  { shortName: 'PA', name: 'Pará' },
  { shortName: 'PB', name: 'Paraíba' },
  { shortName: 'PR', name: 'Paraná' },
  { shortName: 'PE', name: 'Pernambuco' },
  { shortName: 'PI', name: 'Piauí' },
  { shortName: 'RJ', name: 'Rio de Janeiro' },
  { shortName: 'RN', name: 'Rio Grande do Norte' },
  { shortName: 'RS', name: 'Rio Grande do Sul' },
  { shortName: 'RO', name: 'Rondônia' },
  { shortName: 'RR', name: 'Roraima' },
  { shortName: 'SC', name: 'Santa Catarina' },
  { shortName: 'SP', name: 'São Paulo' },
  { shortName: 'SE', name: 'Sergipe' },
  { shortName: 'TO', name: 'Tocantins' },
];
